name: Bug report
description: Something's not working
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Thanks for giving yabridge a shot!
      description: >-
        If you're having issues with plugins not working at all or scans timing
        out then make sure to check out the [troubleshooting common
        issues](https://github.com/robbert-vdh/yabridge#troubleshooting-common-issues)
        section of the readme. You should also read through the [known issues
        and
        fixes](https://github.com/robbert-vdh/yabridge#known-issues-and-fixes)
        section. There may already be a solution or a workaround for the issue
        you're having.
      options:
        - label: >-
            I read through both the troubleshooting and the known issues sections my
            issue wasn't listed there
          required: true
  - type: textarea
    id: description
    attributes:
      label: Problem description
      placeholder: >-
        A short description of what the issue is, and possibly some steps to
        reproduce it if applicable.
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: observed-behaviour
    attributes:
      label: What actually happened?
      placeholder: ...
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      placeholder: e.g. Manjaro, or Ubuntu 38.04
    validations:
      required: true
  - type: input
    id: installation-source
    attributes:
      label: How did you install yabridge?
      placeholder: e.g. directly from the releases page, or the yabridge-git AUR package
    validations:
      required: true
  - type: input
    id: yabridge-version
    attributes:
      label: yabridge version
      placeholder: e.g. 3.5.2, or commit a29f43a
    validations:
      required: true
  - type: input
    id: yabridgectl-version
    attributes:
      label: yabridgectl version
      placeholder: e.g. 3.5.2, or commit a29f43a
    validations:
      required: true
  - type: dropdown
    id: installation-method
    attributes:
      label: Plugin installation method
      description: >-
        From yabridge 2.1.0 onwards you should never have to use the old symlink
        installation method anymore, and it will likely cause issues if you do
        use it.
      options: ["copies", "symlinks"]
    validations:
      required: true
  - type: input
    id: plugin
    attributes:
      label: Plugin
      placeholder: e.g. Sausage Fattener
    validations:
      required: true
  - type: dropdown
    id: plugin-type
    attributes:
      label: Plugin type
      options: ["VST2", "VST3", "both VST2 and VST3"]
    validations:
      required: true
  - type: dropdown
    id: plugin-arch
    attributes:
      label: Plugin architecture
      options: ["64-bit", "32-bit", "both 64-bit and 32-bit"]
    validations:
      required: true
  - type: input
    id: host
    attributes:
      label: Host
      placeholder: e.g. Bitwig Studio 4.0.1
    validations:
      required: true
  - type: input
    id: desktop-environment
    attributes:
      label: Desktop environment or WM
      description: This is only relevant if the issue is related to the plugin's editor.
      placeholder: e.g. KDE Plasma 5.22.4 on Xorg
    validations:
      required: false
  - type: input
    id: gpu-model
    attributes:
      label: GPU model
      description: This is only relevant if the issue is related to the plugin's editor.
      placeholder: e.g. NVIDIA RTX 3090 Ti SUPER
    validations:
      required: false
  - type: input
    id: gpu-drivers
    attributes:
      label: GPU drivers and kernel
      description: This is only relevant if the issue is related to the plugin's editor.
      placeholder: e.g. Mesa 21.1.6 on Linux 5.14.0
    validations:
      required: false
  - type: textarea
    id: debug-log
    attributes:
      label: Debug log
      description: |
        Please also include a debug log if possible. If you are reporting an issue with yabridgectl, then you can omit this section.

        1. First make sure that there are no leftover Wine processes left running in the background using `wineserver -k`.
        2. Launch your host from a terminal using:

           ```bash
           rm -f /tmp/yabridge.log; env YABRIDGE_DEBUG_FILE=/tmp/yabridge.log YABRIDGE_DEBUG_LEVEL=2+editor <host>
           ```

           Where `<host>` is the name of your host, like `bitwig-studio`, `reaper`, or `ardour6`.

        3. Try to scan or load the plugin that's causing issues.
        4. `/tmp/yabridge.log` should now contain a debug log. You can drag this file directly onto the text field below to upload it to GitHub.
    validations:
      required: false
  - type: textarea
    id: other-information
    attributes:
      label: Anything else?
      placeholder: If there's anything else you'd like to add, then you can do so here.
    validations:
      required: false
