blank_issues_enabled: false
contact_links:
  - name: Discord
    about: Support and announcements for yabridge as well as general discussion about plugins and Wine
    url: https://discord.gg/pyNeweqadf
