blank_issues_enabled: true
contact_links:
  - name: Discord
    about: Support and announcements for yabridge, as well as general discussion about using Windows plugins though Wine
    url: https://discord.gg/pyNeweqadf
