blank_issues_enabled: true
contact_links:
  - name: yabridge Discord
    about: Support and announcements for yabridge, and general discussion about using Windows plugins though Wine
    url: https://discord.gg/pyNeweqadf
